/* Creating employees */
INSERT INTO employees (name, username, date_of_birth, hire_date, area, job_title, country, status, tip_rate) VALUES ('Amit Tait', 'atait', '1969-01-02', '2001-01-28', 'Services', 'Manager', 'India', true, 0.0);
INSERT INTO employees (name, username, date_of_birth, hire_date, area, job_title, country, status, tip_rate) VALUES ('Harleen Duncan', 'hduncan', '1974-05-05', '2010-04-09', 'Services', 'Waitress', 'USA', true, 0.9);
INSERT INTO employees (name, username, date_of_birth, hire_date, area, job_title, country, status, tip_rate) VALUES ('Clinton Alvarez', 'calvarez', '1974-12-09', '2004-04-16', 'Kitchen', 'Chef', 'Colombia', true, 0.0);
INSERT INTO employees (name, username, date_of_birth, hire_date, area, job_title, country, status, tip_rate) VALUES ('Romario Greer', 'rgreer', '1975-05-13', '2008-02-19', 'Kitchen', 'Cook', 'Italy', true, 0.0);
INSERT INTO employees (name, username, date_of_birth, hire_date, area, job_title, country, status, tip_rate) VALUES ('Devin Hawes', 'dhawes', '1977-10-02', '2020-07-13', 'Kitchen', 'Dishwasher', 'Germany', false, 0.0);
INSERT INTO employees (name, username, date_of_birth, hire_date, area, job_title, country, status, tip_rate) VALUES ('Arman Kirby', 'akirby', '1990-10-17', '2019-11-19', 'Services', 'Host', 'Canada', true, 0.0);

/* Creating countries */
INSERT INTO countries (name, two_char_code, three_char_code) VALUES ('Afghanistan','AF','AFG')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Aland Islands','AX','ALA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Albania','AL','ALB')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Algeria','DZ','DZA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('American Samoa','AS','ASM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Andorra','AD','AND')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Angola','AO','AGO')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Anguilla','AI','AIA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Antarctica','AQ','ATA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Antigua and Barbuda','AG','ATG')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Argentina','AR','ARG')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Armenia','AM','ARM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Aruba','AW','ABW')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Australia','AU','AUS')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Austria','AT','AUT')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Azerbaijan','AZ','AZE')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Bahamas','BS','BHS')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Bahrain','BH','BHR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Bangladesh','BD','BGD')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Barbados','BB','BRB')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Belarus','BY','BLR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Belgium','BE','BEL')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Belize','BZ','BLZ')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Benin','BJ','BEN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Bermuda','BM','BMU')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Bhutan','BT','BTN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Bolivia','BO','BOL')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Bonaire, Sint Eustatius and Saba','BQ','BES')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Bosnia and Herzegovina','BA','BIH')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Botswana','BW','BWA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Bouvet Island','BV','BVT')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Brazil','BR','BRA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('British Indian Ocean Territory','IO','IOT')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Brunei','BN','BRN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Bulgaria','BG','BGR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Burkina Faso','BF','BFA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Burundi','BI','BDI')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Cambodia','KH','KHM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Cameroon','CM','CMR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Canada','CA','CAN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Cape Verde','CV','CPV')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Cayman Islands','KY','CYM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Central African Republic','CF','CAF')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Chad','TD','TCD')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Chile','CL','CHL')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('China','CN','CHN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Christmas Island','CX','CXR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Cocos (Keeling) Islands','CC','CCK')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Colombia','CO','COL')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Comoros','KM','COM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Congo','CG','COG')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Cook Islands','CK','COK')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Costa Rica','CR','CRI')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Ivory Coast','CI','CIV')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Croatia','HR','HRV')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Cuba','CU','CUB')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Curacao','CW','CUW')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Cyprus','CY','CYP')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Czech Republic','CZ','CZE')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Democratic Republic of the Congo','CD','COD')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Denmark','DK','DNK')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Djibouti','DJ','DJI')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Dominica','DM','DMA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Dominican Republic','DO','DOM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Ecuador','EC','ECU')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Egypt','EG','EGY')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('El Salvador','SV','SLV')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Equatorial Guinea','GQ','GNQ')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Eritrea','ER','ERI')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Estonia','EE','EST')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Ethiopia','ET','ETH')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Falkland Islands (Malvinas)','FK','FLK')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Faroe Islands','FO','FRO')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Fiji','FJ','FJI')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Finland','FI','FIN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('France','FR','FRA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('French Guiana','GF','GUF')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('French Polynesia','PF','PYF')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('French Southern Territories','TF','ATF')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Gabon','GA','GAB')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Gambia','GM','GMB')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Georgia','GE','GEO')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Germany','DE','DEU')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Ghana','GH','GHA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Gibraltar','GI','GIB')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Greece','GR','GRC')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Greenland','GL','GRL')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Grenada','GD','GRD')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Guadaloupe','GP','GLP')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Guam','GU','GUM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Guatemala','GT','GTM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Guernsey','GG','GGY')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Guinea','GN','GIN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Guinea-Bissau','GW','GNB')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Guyana','GY','GUY')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Haiti','HT','HTI')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Heard Island and McDonald Islands','HM','HMD')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Honduras','HN','HND')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Hong Kong','HK','HKG')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Hungary','HU','HUN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Iceland','IS','ISL')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('India','IN','IND')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Indonesia','ID','IDN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Iran','IR','IRN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Iraq','IQ','IRQ')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Ireland','IE','IRL')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Isle of Man','IM','IMN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Israel','IL','ISR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Italy','IT','ITA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Jamaica','JM','JAM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Japan','JP','JPN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Jersey','JE','JEY')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Jordan','JO','JOR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Kazakhstan','KZ','KAZ')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Kenya','KE','KEN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Kiribati','KI','KIR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Kosovo','XK','---')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Kuwait','KW','KWT')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Kyrgyzstan','KG','KGZ')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Laos','LA','LAO')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Latvia','LV','LVA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Lebanon','LB','LBN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Lesotho','LS','LSO')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Liberia','LR','LBR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Libya','LY','LBY')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Liechtenstein','LI','LIE')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Lithuania','LT','LTU')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Luxembourg','LU','LUX')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Macao','MO','MAC')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Macedonia','MK','MKD')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Madagascar','MG','MDG')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Malawi','MW','MWI')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Malaysia','MY','MYS')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Maldives','MV','MDV')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Mali','ML','MLI')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Malta','MT','MLT')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Marshall Islands','MH','MHL')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Martinique','MQ','MTQ')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Mauritania','MR','MRT')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Mauritius','MU','MUS')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Mayotte','YT','MYT')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Mexico','MX','MEX')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Micronesia','FM','FSM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Moldava','MD','MDA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Monaco','MC','MCO')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Mongolia','MN','MNG')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Montenegro','ME','MNE')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Montserrat','MS','MSR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Morocco','MA','MAR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Mozambique','MZ','MOZ')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Myanmar (Burma)','MM','MMR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Namibia','NA','NAM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Nauru','NR','NRU')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Nepal','NP','NPL')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Netherlands','NL','NLD')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('New Caledonia','NC','NCL')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('New Zealand','NZ','NZL')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Nicaragua','NI','NIC')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Niger','NE','NER')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Nigeria','NG','NGA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Niue','NU','NIU')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Norfolk Island','NF','NFK')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('North Korea','KP','PRK')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Northern Mariana Islands','MP','MNP')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Norway','NO','NOR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Oman','OM','OMN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Pakistan','PK','PAK')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Palau','PW','PLW')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Palestine','PS','PSE')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Panama','PA','PAN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Papua New Guinea','PG','PNG')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Paraguay','PY','PRY')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Peru','PE','PER')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Phillipines','PH','PHL')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Pitcairn','PN','PCN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Poland','PL','POL')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Portugal','PT','PRT')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Puerto Rico','PR','PRI')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Qatar','QA','QAT')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Reunion','RE','REU')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Romania','RO','ROU')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Russia','RU','RUS')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Rwanda','RW','RWA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Saint Barthelemy','BL','BLM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Saint Helena','SH','SHN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Saint Kitts and Nevis','KN','KNA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Saint Lucia','LC','LCA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Saint Martin','MF','MAF')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Saint Pierre and Miquelon','PM','SPM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Saint Vincent and the Grenadines','VC','VCT')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Samoa','WS','WSM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('San Marino','SM','SMR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Sao Tome and Principe','ST','STP')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Saudi Arabia','SA','SAU')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Senegal','SN','SEN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Serbia','RS','SRB')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Seychelles','SC','SYC')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Sierra Leone','SL','SLE')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Singapore','SG','SGP')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Sint Maarten','SX','SXM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Slovakia','SK','SVK')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Slovenia','SI','SVN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Solomon Islands','SB','SLB')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Somalia','SO','SOM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('South Africa','ZA','ZAF')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('South Georgia and the South Sandwich Islands','GS','SGS')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('South Korea','KR','KOR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('South Sudan','SS','SSD')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Spain','ES','ESP')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Sri Lanka','LK','LKA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Sudan','SD','SDN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Suriname','SR','SUR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Svalbard and Jan Mayen','SJ','SJM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Swaziland','SZ','SWZ')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Sweden','SE','SWE')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Switzerland','CH','CHE')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Syria','SY','SYR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Taiwan','TW','TWN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Tajikistan','TJ','TJK')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Tanzania','TZ','TZA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Thailand','TH','THA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Timor-Leste (East Timor)','TL','TLS')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Togo','TG','TGO')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Tokelau','TK','TKL')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Tonga','TO','TON')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Trinidad and Tobago','TT','TTO')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Tunisia','TN','TUN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Turkey','TR','TUR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Turkmenistan','TM','TKM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Turks and Caicos Islands','TC','TCA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Tuvalu','TV','TUV')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Uganda','UG','UGA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Ukraine','UA','UKR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('United Arab Emirates','AE','ARE')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('United Kingdom','GB','GBR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('United States','US','USA')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('United States Minor Outlying Islands','UM','UMI')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Uruguay','UY','URY')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Uzbekistan','UZ','UZB')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Vanuatu','VU','VUT')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Vatican City','VA','VAT')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Venezuela','VE','VEN')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Vietnam','VN','VNM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Virgin Islands, British','VG','VGB')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Virgin Islands, US','VI','VIR')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Wallis and Futuna','WF','WLF')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Western Sahara','EH','ESH')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Yemen','YE','YEM')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Zambia','ZM','ZMB')
INSERT INTO countries (name, two_char_code, three_char_code) VALUES('Zimbabwe','ZW','ZWE');